<?php

declare(strict_types=1);

/**
 * Validates this theme's `capell.json` manifest — generated by
 * `capell:make-theme` — mirrors the shape existing theme packages'
 * `ThemePackageManifestTest` files assert on: stable `themeKey`, `extends`
 * pointing at the default theme, `kind: "theme"`, and a runtime provider
 * entry matching the generated service provider.
 *
 * @return array<string, mixed>
 */
function callOutManifestJson(): array
{
    $path = __DIR__ . '/../../capell.json';

    throw_unless(is_file($path), RuntimeException::class, 'Expected capell.json at ' . $path . '.');

    $decoded = json_decode((string) file_get_contents($path), true, flags: JSON_THROW_ON_ERROR);

    throw_unless(is_array($decoded), RuntimeException::class, 'Expected a JSON object in capell.json.');

    /** @var array<string, mixed> $decoded */
    return $decoded;
}

it('declares a stable theme key extending the default theme', function (): void {
    $manifest = callOutManifestJson();

    expect($manifest['kind'])->toBe('theme')
        ->and($manifest['themeKey'])->toBe('call-out')
        ->and($manifest['extends'])->toBe('default')
        ->and($manifest['name'])->toBe('capell-app/theme-call-out');
});

it('registers its own runtime service provider', function (): void {
    $manifest = callOutManifestJson();
    $runtimeProviders = data_get($manifest, 'providers.runtime');

    throw_unless(is_array($runtimeProviders), RuntimeException::class, 'Expected providers.runtime to be an array.');

    expect($runtimeProviders)->toContain('Capell\ThemeStudio\CallOut\\CallOutThemeServiceProvider');
});

it('requires theme-foundation and layout-builder', function (): void {
    $manifest = callOutManifestJson();
    $requiredDependencies = data_get($manifest, 'dependencies.requires');

    throw_unless(is_array($requiredDependencies), RuntimeException::class, 'Expected dependencies.requires to be an array.');

    expect($requiredDependencies)
        ->toContain('capell-app/theme-foundation')
        ->toContain('capell-app/layout-builder');
});
