<?php

declare(strict_types=1);

use Capell\SeoSuite\Enums\SeoCheckModeEnum;

return [
    'ai_creator' => [
        'enabled' => env('AI_CREATOR_ENABLED', true),
    ],
    'search_console' => [
        'enabled' => env('CAPELL_SEO_TOOLS_SEARCH_CONSOLE_ENABLED', false),
        'credentials_path' => env('CAPELL_SEO_TOOLS_SEARCH_CONSOLE_CREDENTIALS'),
        'property_url' => env('CAPELL_SEO_TOOLS_SEARCH_CONSOLE_PROPERTY_URL'),
        'timeout' => env('CAPELL_SEO_TOOLS_SEARCH_CONSOLE_TIMEOUT', 20),
    ],
    'pagespeed' => [
        'enabled' => env('CAPELL_SEO_SUITE_PAGESPEED_ENABLED', true),
        'api_key' => env('CAPELL_SEO_SUITE_PAGESPEED_API_KEY'),
        'timeout' => env('CAPELL_SEO_SUITE_PAGESPEED_TIMEOUT', 90),
        'weekly_schedule' => env('CAPELL_SEO_SUITE_PAGESPEED_WEEKLY_SCHEDULE', 'monday_0600'),
    ],
    'ai_discovery' => [
        'crawler_policy' => env('CAPELL_SEO_SUITE_AI_DISCOVERY_CRAWLER_POLICY', 'search_visible_training_restricted'),
        'crawler_policy_presets' => [
            'search_visible_training_restricted' => [
                'rules' => [
                    'OAI-SearchBot' => 'allow',
                    'GPTBot' => 'disallow',
                    'ChatGPT-User' => 'allow',
                    'ClaudeBot' => 'disallow',
                    'Claude-SearchBot' => 'allow',
                    'Claude-User' => 'allow',
                    'PerplexityBot' => 'allow',
                    'Google-Extended' => 'disallow',
                    'CCBot' => 'disallow',
                ],
            ],
            'open' => [
                'rules' => [
                    'OAI-SearchBot' => 'allow',
                    'GPTBot' => 'allow',
                    'ChatGPT-User' => 'allow',
                    'ClaudeBot' => 'allow',
                    'Claude-SearchBot' => 'allow',
                    'Claude-User' => 'allow',
                    'PerplexityBot' => 'allow',
                    'Google-Extended' => 'allow',
                    'CCBot' => 'allow',
                ],
            ],
            'restrictive' => [
                'rules' => [
                    'OAI-SearchBot' => 'disallow',
                    'GPTBot' => 'disallow',
                    'ChatGPT-User' => 'disallow',
                    'ClaudeBot' => 'disallow',
                    'Claude-SearchBot' => 'disallow',
                    'Claude-User' => 'disallow',
                    'PerplexityBot' => 'disallow',
                    'Google-Extended' => 'disallow',
                    'CCBot' => 'disallow',
                ],
            ],
        ],
        'default_crawler_rules' => [
            [
                'provider' => 'OpenAI',
                'user_agent' => 'OAI-SearchBot',
                'purpose' => 'search',
                'directive' => 'allow',
                'path' => '/',
                'source_url' => 'https://platform.openai.com/docs/bots',
                'notes' => 'ChatGPT search visibility crawler.',
            ],
            [
                'provider' => 'OpenAI',
                'user_agent' => 'GPTBot',
                'purpose' => 'training',
                'directive' => 'disallow',
                'path' => '/',
                'source_url' => 'https://platform.openai.com/docs/bots',
                'notes' => 'OpenAI training crawler control.',
            ],
            [
                'provider' => 'OpenAI',
                'user_agent' => 'ChatGPT-User',
                'purpose' => 'user_triggered',
                'directive' => 'allow',
                'path' => '/',
                'source_url' => 'https://platform.openai.com/docs/bots',
                'notes' => 'User-triggered ChatGPT fetch control; robots.txt may not apply to every user-initiated action.',
            ],
            [
                'provider' => 'Anthropic',
                'user_agent' => 'ClaudeBot',
                'purpose' => 'training',
                'directive' => 'disallow',
                'path' => '/',
                'source_url' => 'https://support.claude.com/en/articles/8896518-does-anthropic-crawl-data-from-the-web-and-how-can-site-owners-block-the-crawler',
                'notes' => 'Anthropic crawler control.',
            ],
            [
                'provider' => 'Anthropic',
                'user_agent' => 'Claude-SearchBot',
                'purpose' => 'search',
                'directive' => 'allow',
                'path' => '/',
                'source_url' => 'https://support.claude.com/en/articles/8896518-does-anthropic-crawl-data-from-the-web-and-how-can-site-owners-block-the-crawler',
                'notes' => 'Anthropic search visibility crawler.',
            ],
            [
                'provider' => 'Anthropic',
                'user_agent' => 'Claude-User',
                'purpose' => 'user_triggered',
                'directive' => 'allow',
                'path' => '/',
                'source_url' => 'https://support.claude.com/en/articles/8896518-does-anthropic-crawl-data-from-the-web-and-how-can-site-owners-block-the-crawler',
                'notes' => 'User-triggered Claude fetch control.',
            ],
            [
                'provider' => 'Perplexity',
                'user_agent' => 'PerplexityBot',
                'purpose' => 'search',
                'directive' => 'allow',
                'path' => '/',
                'source_url' => 'https://docs.perplexity.ai/guides/bots',
                'notes' => 'Perplexity search indexing crawler.',
            ],
            [
                'provider' => 'Google',
                'user_agent' => 'Google-Extended',
                'purpose' => 'training',
                'directive' => 'disallow',
                'path' => '/',
                'source_url' => 'https://developers.google.com/search/docs/crawling-indexing/google-common-crawlers',
                'notes' => 'Gemini training and grounding control token.',
            ],
            [
                'provider' => 'Common Crawl',
                'user_agent' => 'CCBot',
                'purpose' => 'generic_crawl',
                'directive' => 'disallow',
                'path' => '/',
                'source_url' => 'https://commoncrawl.org/ccbot',
                'notes' => 'Common Crawl dataset crawler.',
            ],
        ],
    ],
    'publish_gates' => [
        'checks' => [
            'meta_title' => SeoCheckModeEnum::Blocker->value,
            'meta_description' => SeoCheckModeEnum::Blocker->value,
            'robots' => SeoCheckModeEnum::Blocker->value,
            'canonical' => SeoCheckModeEnum::Warning->value,
            'schema' => SeoCheckModeEnum::Warning->value,
            'internal_links' => SeoCheckModeEnum::Warning->value,
            'social_image' => SeoCheckModeEnum::Warning->value,
            'redirects' => SeoCheckModeEnum::Blocker->value,
            'search_console' => SeoCheckModeEnum::Ignored->value,
        ],
    ],
];
