<?php

declare(strict_types=1);

return [
    'enabled' => env('CAPELL_INSIGHTS_ENABLED', true),
    'route_prefix' => 'capell/insights',
    'validate_beacon_origin' => true,
    'require_signed_beacons' => false,
    'honor_privacy_signals' => true,
    'signed_beacon_ttl_minutes' => 60,
    'allowed_beacon_origins' => [],
    'track_page_views' => true,
    'track_clicks' => true,
    'track_forms' => false,
    'automatic_click_tracking' => true,
    'consent_banner_enabled' => env('CAPELL_INSIGHTS_CONSENT_BANNER_ENABLED', true),
    'screenshot_fixtures_enabled' => env('CAPELL_INSIGHTS_SCREENSHOT_FIXTURES_ENABLED', false),
    'require_consent_for_all_regions' => false,
    'default_consent_region' => null,
    'policy_version' => '1.0',
    'consent_expires_days' => 180,
    'retention_days' => 365,
    'purge_batch_size' => 500,
    'rollup_rebuild_days' => 30,
    'dashboard_cache_ttl_seconds' => 60,
    'session_timeout_minutes' => 30,
    'hash_visitor_data' => true,
    'hash_salt' => null,
    'ignored_ips' => [],
    'ignored_user_agents' => [
        '*bot*',
        '*crawler*',
        '*spider*',
        '*preview*',
        '*monitor*',
        '*uptime*',
        '*lighthouse*',
        '*pagespeed*',
        '*headlesschrome*',
        '*pingdom*',
        '*gtmetrix*',
    ],
    'ignored_paths' => [
        '/admin*',
        '/livewire*',
        '/capell/insights*',
        '/_debugbar*',
        '/_clockwork*',
        '/storage*',
    ],
    'ignored_selectors' => [
        '[data-capell-insights-ignore]',
        '[wire\\:click]',
    ],
    'tables' => [
        'visits' => 'insights_visits',
        'consents' => 'insights_consents',
        'events' => 'insights_events',
        'daily_rollups' => 'insights_daily_rollups',
    ],
];
