<?php

declare(strict_types=1);

require_once __DIR__ . '/audit-package-security.php';

const CAPELL_SECURITY_SURFACE_REPORT_PATH = 'docs/package-security-surface.md';

if (realpath((string) ($_SERVER['SCRIPT_FILENAME'] ?? '')) === __FILE__) {
    $root = dirname(__DIR__);
    $report = capell_security_surface_report_markdown($root);
    $path = $root . DIRECTORY_SEPARATOR . CAPELL_SECURITY_SURFACE_REPORT_PATH;
    $check = in_array('--check', $argv, true);

    if ($check) {
        $current = is_file($path) ? (string) file_get_contents($path) : '';

        if ($current !== $report) {
            fwrite(STDERR, CAPELL_SECURITY_SURFACE_REPORT_PATH . " is stale; run php scripts/generate-package-security-surface-report.php\n");

            throw new RuntimeException(CAPELL_SECURITY_SURFACE_REPORT_PATH . ' is stale.');
        }

        echo CAPELL_SECURITY_SURFACE_REPORT_PATH . " is current.\n";

        return;
    }

    file_put_contents($path, $report);
    echo 'Wrote ' . CAPELL_SECURITY_SURFACE_REPORT_PATH . "\n";
}

function capell_security_surface_report_markdown(string $root): string
{
    $rows = capell_security_surface_report_rows($root);
    $summary = capell_security_surface_report_summary($rows);

    $lines = [
        '# Package Security Surface Report',
        '',
        '<!-- This file is generated by scripts/generate-package-security-surface-report.php. -->',
        '<!-- prettier-ignore-start -->',
        '',
        'This generated report is a technical operator reference for reviewing package install risk. It summarizes public routes, webhooks, throttling, signed or tokenized entry points, sensitive fields, admin authorization posture, and public-output cache posture from package manifests.',
        '',
        'For non-technical review, start with the risk column and the summary counts. `critical` or `sensitive` packages deserve a closer implementation review before install, especially when they expose public routes, webhooks, customer data, payments, agent access, or signed URLs.',
        '',
        'Cache posture uses three terms: `safe` means public output is expected to avoid admin/editor metadata, `cacheable` means the package declares public output that can be cached, and `sensitive output` means responses may vary by customer, subject, token, or other private context.',
        '',
        '## Summary',
        '',
        '- Packages: ' . count($rows),
        '- Packages with public routes: ' . $summary['packagesWithPublicRoutes'],
        '- Public routes: ' . $summary['publicRoutes'],
        '- Webhook routes: ' . $summary['webhookRoutes'],
        '- Throttled routes: ' . $summary['throttledRoutes'],
        '- Signed or tokenized routes: ' . $summary['signedOrTokenizedRoutes'],
        '- Sensitive fields: ' . $summary['sensitiveFields'],
        '- Anonymous-output-safe packages: ' . $summary['anonymousOutputSafePackages'],
        '',
        '## Package Surface',
        '',
        '| Package | Risk | Public routes | Webhooks | Throttled | Signed/tokenized | Sensitive fields | Admin authorization | Cache posture |',
        '| --- | --- | ---: | --- | --- | --- | --- | --- | --- |',
    ];

    foreach ($rows as $row) {
        $lines[] = sprintf(
            '| %s | %s | %d | %s | %s | %s | %s | %s | %s |',
            capell_security_surface_markdown($row['package']),
            capell_security_surface_markdown($row['riskTier']),
            count($row['publicRoutes']),
            capell_security_surface_list($row['webhookRoutes']),
            capell_security_surface_list($row['throttledRoutes']),
            capell_security_surface_list($row['signedOrTokenizedRoutes']),
            capell_security_surface_list($row['sensitiveFields']),
            capell_security_surface_markdown($row['adminAuthorization']),
            capell_security_surface_markdown($row['cachePosture']),
        );
    }

    $lines[] = '';
    $lines[] = '<!-- prettier-ignore-end -->';
    $lines[] = '';

    return implode("\n", $lines);
}

/**
 * @return list<array{
 *     package: string,
 *     riskTier: string,
 *     publicRoutes: list<string>,
 *     webhookRoutes: list<string>,
 *     throttledRoutes: list<string>,
 *     signedOrTokenizedRoutes: list<string>,
 *     sensitiveFields: list<string>,
 *     adminAuthorization: string,
 *     cachePosture: string
 * }>
 */
function capell_security_surface_report_rows(string $root): array
{
    $rows = [];

    foreach (capell_security_manifest_payloads($root) as $manifest) {
        $security = capell_security_array_value($manifest['security'] ?? null);
        $publicSurface = capell_security_array_value($security['publicSurface'] ?? null);
        $sensitiveData = capell_security_array_value($security['sensitiveData'] ?? null);
        $publicOutput = capell_security_array_value($security['publicOutput'] ?? null);
        $adminSurface = capell_security_array_value($security['adminSurface'] ?? null);
        $performance = capell_security_array_value($manifest['performance'] ?? null);
        $cacheSafety = capell_security_array_value($performance['cacheSafety'] ?? null);
        $packageName = is_string($manifest['name'] ?? null) ? $manifest['name'] : 'unknown';
        $riskTier = is_string($security['riskTier'] ?? null) ? $security['riskTier'] : 'unknown';

        $rows[] = [
            'package' => $packageName,
            'riskTier' => $riskTier,
            'publicRoutes' => capell_security_string_list($publicSurface['routeNames'] ?? []),
            'webhookRoutes' => capell_security_string_list($publicSurface['webhookRoutes'] ?? []),
            'throttledRoutes' => capell_security_string_list($publicSurface['throttledRoutes'] ?? []),
            'signedOrTokenizedRoutes' => capell_security_surface_signed_or_tokenized_routes($publicSurface),
            'sensitiveFields' => capell_security_surface_sensitive_fields($sensitiveData),
            'adminAuthorization' => capell_security_surface_admin_authorization($adminSurface),
            'cachePosture' => capell_security_surface_cache_posture($publicOutput, $cacheSafety),
        ];
    }

    usort($rows, static fn (array $first, array $second): int => $first['package'] <=> $second['package']);

    return $rows;
}

/**
 * @param  list<array{
 *     package: string,
 *     riskTier: string,
 *     publicRoutes: list<string>,
 *     webhookRoutes: list<string>,
 *     throttledRoutes: list<string>,
 *     signedOrTokenizedRoutes: list<string>,
 *     sensitiveFields: list<string>,
 *     adminAuthorization: string,
 *     cachePosture: string
 * }>  $rows
 * @return array{
 *     packagesWithPublicRoutes: int,
 *     publicRoutes: int,
 *     webhookRoutes: int,
 *     throttledRoutes: int,
 *     signedOrTokenizedRoutes: int,
 *     sensitiveFields: int,
 *     anonymousOutputSafePackages: int
 * }
 */
function capell_security_surface_report_summary(array $rows): array
{
    return [
        'packagesWithPublicRoutes' => count(array_filter($rows, static fn (array $row): bool => $row['publicRoutes'] !== [])),
        'publicRoutes' => array_sum(array_map(static fn (array $row): int => count($row['publicRoutes']), $rows)),
        'webhookRoutes' => array_sum(array_map(static fn (array $row): int => count($row['webhookRoutes']), $rows)),
        'throttledRoutes' => array_sum(array_map(static fn (array $row): int => count($row['throttledRoutes']), $rows)),
        'signedOrTokenizedRoutes' => array_sum(array_map(static fn (array $row): int => count($row['signedOrTokenizedRoutes']), $rows)),
        'sensitiveFields' => array_sum(array_map(static fn (array $row): int => count($row['sensitiveFields']), $rows)),
        'anonymousOutputSafePackages' => count(array_filter($rows, static fn (array $row): bool => str_starts_with($row['cachePosture'], 'safe'))),
    ];
}

/**
 * @param  array<string, mixed>  $publicSurface
 * @return list<string>
 */
function capell_security_surface_signed_or_tokenized_routes(array $publicSurface): array
{
    $routes = [
        ...capell_security_string_list($publicSurface['signedRoutes'] ?? []),
        ...capell_security_string_list($publicSurface['tokenizedRoutes'] ?? []),
    ];

    sort($routes);

    return array_values(array_unique($routes));
}

/**
 * @param  array<string, mixed>  $sensitiveData
 * @return list<string>
 */
function capell_security_surface_sensitive_fields(array $sensitiveData): array
{
    $fields = [
        ...capell_security_string_list($sensitiveData['encryptedFields'] ?? []),
        ...capell_security_string_list($sensitiveData['hashedTokenFields'] ?? []),
        ...capell_security_plaintext_justification_fields($sensitiveData['plaintextJustifications'] ?? []),
    ];

    sort($fields);

    return array_values(array_unique($fields));
}

/**
 * @param  array<string, mixed>  $publicOutput
 * @param  array<string, mixed>  $cacheSafety
 */
/**
 * @param  array<string, mixed>  $adminSurface
 */
function capell_security_surface_admin_authorization(array $adminSurface): string
{
    $authorization = is_string($adminSurface['authorization'] ?? null)
        ? $adminSurface['authorization']
        : 'not declared';
    $permissions = capell_security_string_list($adminSurface['permissions'] ?? []);

    if ($permissions === []) {
        return $authorization;
    }

    return sprintf('%s; %d permission%s', $authorization, count($permissions), count($permissions) === 1 ? '' : 's');
}

/**
 * @param  array<string, mixed>  $publicOutput
 * @param  array<string, mixed>  $cacheSafety
 */
function capell_security_surface_cache_posture(array $publicOutput, array $cacheSafety): string
{
    $cacheSafe = ($publicOutput['cacheSafe'] ?? null) === true ? 'safe' : 'not safe';
    $cacheable = ($cacheSafety['cacheable'] ?? null) === true ? 'cacheable' : 'not cacheable';
    $sensitive = ($cacheSafety['sensitiveOutput'] ?? null) === true ? 'sensitive output' : 'no sensitive output';
    $variesBy = capell_security_string_list($cacheSafety['variesBy'] ?? []);

    return sprintf(
        '%s; %s; %s; varies by %s',
        $cacheSafe,
        $cacheable,
        $sensitive,
        $variesBy === [] ? 'none' : implode(', ', $variesBy),
    );
}

/**
 * @param  list<string>  $items
 */
function capell_security_surface_list(array $items): string
{
    if ($items === []) {
        return '-';
    }

    return capell_security_surface_markdown(implode('<br>', $items));
}

function capell_security_surface_markdown(string $value): string
{
    return str_replace('|', '&#124;', $value);
}
