<?php

declare(strict_types=1);

namespace Capell\Deployments\Actions;

use Capell\Deployments\Data\ComposerRequirementData;
use Capell\Deployments\Data\PublishComposerChangeResultData;
use Capell\Deployments\Enums\InstallPolicy;
use Capell\Deployments\Models\DeploymentConnection;
use Capell\Deployments\Services\GitProvider\GitProviderFactory;
use Illuminate\Support\Str;
use Lorisleiva\Actions\Concerns\AsAction;

final class PublishComposerRequirementAction
{
    use AsAction;

    public function __construct(private readonly GitProviderFactory $factory) {}

    public function handle(ComposerRequirementData $requirement, DeploymentConnection $connection): PublishComposerChangeResultData
    {
        $provider = $this->factory->for($connection);
        $slug = str($requirement->label ?? $requirement->composerName)->afterLast('/')->slug()->toString();

        $composerJson = $provider->getFile($connection, 'composer.json');
        $patched = PrepareComposerRequirementCommitAction::run($requirement, $composerJson);

        if ($connection->install_policy === InstallPolicy::DirectCommit) {
            $sha = $provider->commitFiles(
                $connection,
                $connection->default_branch,
                'Add extension ' . $requirement->composerName,
                [$patched],
            );

            return new PublishComposerChangeResultData(provider: $connection->provider, commitSha: $sha);
        }

        $branchName = 'capell/add-extension-' . $slug . '-' . Str::random(6);

        $provider->createBranch($connection, $branchName, $provider->getBranchCommitSha($connection, $connection->default_branch));
        $provider->commitFiles($connection, $branchName, 'Add extension ' . $requirement->composerName, [$patched]);

        $pr = $provider->openPullRequest(
            $connection,
            $branchName,
            sprintf('Add extension %s', $requirement->composerName),
            "Auto-generated by Capell.\n\nThis PR adds `{$requirement->composerName}` to your Capell instance.",
        );

        if ($connection->install_policy === InstallPolicy::PullRequestAutoMerge) {
            $provider->enableAutoMerge($connection, $pr->id);
        }

        return new PublishComposerChangeResultData(
            provider: $connection->provider,
            pullRequestUrl: $pr->url,
            pullRequestId: is_int($pr->id) ? $pr->id : null,
        );
    }
}
