<?php

declare(strict_types=1);

/**
 * Validates this theme's `capell.json` manifest — generated by
 * `capell:make-theme` — mirrors the shape existing theme packages'
 * `ThemePackageManifestTest` files assert on: stable `themeKey`, `extends`
 * pointing at the default theme, `kind: "theme"`, and a runtime provider
 * entry matching the generated service provider.
 *
 * @return array<string, mixed>
 */
function readingRoomManifestJson(): array
{
    $path = __DIR__ . '/../../capell.json';

    throw_unless(is_file($path), RuntimeException::class, 'Expected capell.json at ' . $path . '.');

    $decoded = json_decode((string) file_get_contents($path), true, flags: JSON_THROW_ON_ERROR);

    throw_unless(is_array($decoded), RuntimeException::class, 'Expected a JSON object in capell.json.');

    return $decoded;
}

it('declares a stable theme key extending the default theme', function (): void {
    $manifest = readingRoomManifestJson();

    expect($manifest['kind'])->toBe('theme')
        ->and($manifest['themeKey'])->toBe('reading-room')
        ->and($manifest['extends'])->toBe('default')
        ->and($manifest['name'])->toBe('capell-app/theme-reading-room');
});

it('registers its own runtime service provider', function (): void {
    $manifest = readingRoomManifestJson();

    expect($manifest['providers']['runtime'])->toContain('Capell\ThemeStudio\ReadingRoom\\ReadingRoomThemeServiceProvider');
});

it('requires theme-foundation and layout-builder', function (): void {
    $manifest = readingRoomManifestJson();

    expect($manifest['dependencies']['requires'])
        ->toContain('capell-app/theme-foundation')
        ->toContain('capell-app/layout-builder');
});
